language: rust
sudo: false
cache: cargo
matrix:
  include:
  - rust: stable
    name: build
    env: RUST_BACKTRACE=1
    addons:
      firefox: latest
      chrome: stable
    before_script:
    - "(test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)"
    - cargo install-update -a
    - rustup target add wasm32-unknown-unknown
    - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s --
      -f
    script:
    - rm -rf .cargo
    - cargo check
    - cargo check --target wasm32-unknown-unknown
    - cargo check                                 --no-default-features
    - cargo check --target wasm32-unknown-unknown --no-default-features
    - cargo check                                 --no-default-features --features
      console_error_panic_hook
    - cargo check --target wasm32-unknown-unknown --no-default-features --features
      console_error_panic_hook
    - wasm-pack build
    - wasm-pack test --chrome --firefox --headless
  - rust: beta
    env: RUST_BACKTRACE=1
    before_script:
    - rm -rf .cargo
    - "(test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)"
    - cargo install-update -a
    - rustup target add wasm32-unknown-unknown
    script:
    - rm -rf .cargo
    - cargo check
    - cargo check --target wasm32-unknown-unknown
    - cargo check                                 --no-default-features
    - cargo check --target wasm32-unknown-unknown --no-default-features
    - cargo check                                 --no-default-features --features
      console_error_panic_hook
    - cargo check --target wasm32-unknown-unknown --no-default-features --features
      console_error_panic_hook
before_deploy: cd pkg
deploy:
  provider: npm
  email: ben.b.brunton@gmail.com
  skip_cleanup: true
  api_key:
    secure: eDDTogUEhKOBAaETPgzOIJD6lelvxs+o6BF30tLPmtSuxbMWfzfWA2gOzk/2c9mbuPPxfPBsUjzLNzHh2N8rV/adro+cJ/Hlb0pBzldWJjF7QmFbFPSeN9QBi5g0QGq6xdSBJEZTLJFb4VGF+3cElvDJtBJOeSiUJfAoicAYpZomWOaq0CSYr+ltZ6Nf/yxgAdG5JRXzW66A+KVA8NvxbgOFf5ozgjZposmU2D9C1xPyGj6fN0S/zKyysXfHhLdOU2Zzxuh6+5QuLoOMxnR30ZQb0xjR6Gr3yxD2nL3donHiGPC2CKgdc+AQRzb3W3z66fBhzoGAXJVLD491Ury+13N7R4Q5p3VC+62paDwN/p99/fYawg+MTl/ayLy9mjVFbb33gXJKjURIyQk6eM8PoIEsyhBZBU14DgcAmZ9JKYSQHZoqkqZ2rvzvrfADvltKyVgHMGfwXKULWKaIPt5UH9Rl9/RG/AWUtDQo9O0MtKcjE0mjgIs6lyoEarxQNiYq/wBG52Wme5Db8IXTww/ZU4ZjcunFD0P7RtZkLsH1QBJMPqCbQmsIrQEO0lP8IdP1uK+B0CYWnzCewBJ5Hoi/d4JuvQDBpQCs53LyfLkphzQXrLR62EwfbcLrXRvCDn1kpU1ZiDisZPutbHSq4uOfFzd/MTTcQ/o2SQbVYPwCT6I=
  on:
    tags: true
    branch: master
    rust: stable
    name: build
notifications:
  slack:
    secure: ByVMId+QR/V7yO4zQaPr8zr8zPZoRT5w5jdSxgiXsgGpflIx0t0yXlLutVaS5223g4tfJSf7V65WhACsrRWF3F9oZu34mvo84x+5ZsaRLJOovC32dqpXvH5DyamF+Hq1SdheGQVXvUk6RO57l2UNzuT2WlX7/6wUNj58PCEoZ3cFkAQVZ9P347nomahQDnx0RAJypTjBs37alRMqnpUYF68SeYdD13+ISLFqCMH3rEL2XkhEcO6JeLRwadmvTt9edc0DxAUY5qeDf2iRptec3jxGtcS+Sgisg2eYgT0YbONz5Ep9OZ2RjJr242NLRQ6cZMCUWl4Sxm7ojqaIIigUS9AHd5uzztK6RIrJfcHH6cXBCl9Gfhz+fdH0ERA8VhuOZ8f67fu7KNjdoy00spuvMN110P8CVbZvytWYEPpIoESUSxWlEsPGP/r8cGGX/zwzfCtq7J/6DWZijIwG+idi2giCzcx9MbMst5Hmx7+rBeVkYBnZCtutWVPSafcJjUChTUna16rnJhIbUh0kDDoFB1u1FeI8sx6+NFr1fCckroYSXzpeOZ8gj+raD1d5mlO3sGHhSCKmBy78BFveSdzpE+vBMGQN28H8Ma3LcrIZZIoAn+FGeXQZhC7UT+bSJp1dGYjzph+V8zV6nXWWAb8dkxVaZ9zx/BCUK0xIBR1QVxs=
